// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Hospital;

namespace unq_iisoft_2021_c1_hospitalWebSite.Migrations
{
    [DbContext(typeof(SanatorioContext))]
    [Migration("20210524024845_Sanatorio")]
    partial class Sanatorio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Models.Hospital.Especialidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Models.Hospital.Medico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreYApellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RolEnEspecialidadID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EspecialidadID");

                    b.HasIndex("RolEnEspecialidadID");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("Models.Hospital.Nota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URLImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URLNotaCompleta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("Models.Hospital.ObraSocial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ObraSocial");
                });

            modelBuilder.Entity("Models.Hospital.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObraSocialID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ObraSocialID");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("Models.Hospital.Rol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Models.Hospital.Turno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Turno");
                });

            modelBuilder.Entity("Models.Hospital.Usuario", b =>
                {
                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("TEXT");

                    b.HasKey("Mail");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Models.Hospital.Medico", b =>
                {
                    b.HasOne("Models.Hospital.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Hospital.Rol", "RolEnEspecialidad")
                        .WithMany()
                        .HasForeignKey("RolEnEspecialidadID");

                    b.Navigation("Especialidad");

                    b.Navigation("RolEnEspecialidad");
                });

            modelBuilder.Entity("Models.Hospital.Plan", b =>
                {
                    b.HasOne("Models.Hospital.ObraSocial", "ObraSocial")
                        .WithMany("Planes")
                        .HasForeignKey("ObraSocialID");

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Models.Hospital.ObraSocial", b =>
                {
                    b.Navigation("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
